### ISSUE TITLE
Backend (REST API) : Models -> Posts

### ISSUE THREAD

**Issue by srijan-singh** [srijan-singh/social-media#2]
Create Post Model and API :  Node, Express

**Comment by somanshusingh** [comment]
hi,
`var express = require('express')
  , bodyParser = require('body-parser');

var app = express();

app.use(bodyParser.json());

app.post('/', function(request, response){
  console.log(request.body);      // your JSON
   response.send(request.body);    // echo the result back
});

app.listen(3000);`

**Comment by srijan-singh** [comment]
Completed!
